### ISSUE TITLE
Teensy 4.1 does not find Sysex folder on SD card

### ISSUE THREAD

**Issue by rolfdegen** [TobiasVanDyk/Microdexed-Synth-Variations#1]
I use Teensy 4.1, DAC PCM5102A and LCD 2X16. I use Synth-Variation Microdexed3. Unfortunately without success. No sound. See my post on discord microdexed 
![20241026_141647](https://github.com/user-attachments/assets/2b0dea12-a35e-4744-9986-32516708c6e8)

https://discord.com/channels/1017534928616951819/1017539452589056132

**Comment by TobiasVanDyk** [comment]
Hi Rolf
I remember you from your Jeannie Synth on the Teensy Forum
I would search the source code for the \*ERROR\* string and work back from there?
Undoubtedly it is just something to do with the SD file system
best wishes
Tobie van Dyk

**Comment by TobiasVanDyk** [comment]
Also read [**here**](https://codeberg.org/positionhigh/MicroDexed-touch/issues/142)

**Comment by rolfdegen** [comment]
The version Microdexed3 with Teensy 4.0 and SD card reader (from Audio Board Rev D) and PCM5102A works. Thanks for the support.

Pic https://i.ibb.co/zN56y7V/20241031-115126.jpg

![20241031-115126](https://github.com/user-attachments/assets/c2757964-0a0c-41ce-9191-833fe7f1f80f)
